name: stackoverflow
dependencies:
  - numpy==1.20.* 
  - pandas==1.2.*
  - mallet==2.0.8 
  - nltk==3.4.4 
  - en_core_web_sm==3.0.0 
  - seaborn==0.11.1 
  - wordcloud==1.8.1 
  - gensim==3.8.3 
  - spacy==3.0.3 
  - matplotlib==3.3.4 
  - plotly==4.14.3 
  - pyLDAvis==3.2.0