name: stackoverflow
channels:
  - defaults
dependencies:
  - en_core_web_sm==3.0.0
  - textblob==0.15.3
  - scipy==1.5.4
  - matplotlib==3.3.2
  - nltk==3.5
  - seaborn==0.11.1
  - spacy==3.0.3
  - gensim==3.8.3
  - wordcloud==1.8.1
  - pandas==1.2.1
  - numpy==1.19.3
  - kaggle==1.5.10
  - pickle5==0.0.11
  - plotly==4.14.3
  - pyLDAvis==3.2.2